### ISSUE TITLE
fails to flash firmware

### ISSUE THREAD

**Issue by josejlpd** [igo-r/Lumi-Router-JN5169#1]
hi i am having trouble flashing firmware to switch mode my xiaomi mijia gateway

root@Xiaomi_Mijia_Gateway:~# jnflash /tmp/Lumi_Router.bin
Flash /tmp/Lumi_Router.bin
JennicModuleProgrammer Version: 0.11 (r1234)
Logging Serial port opened at iInitialSpeed (= 38400) to /tmp/flasher.log
Setting baudrate for port 3 to 1000000
Error setting (bootloader) baudrate to iProgramSpeed (1000000) (2)
Logging Error setting (bootloader) baudrate to iProgramSpeed (= 1000000) to /tmp/flasher.log
Error setting (bootloader) baudrate to iProgramSpeed (1000000) (1)
Logging Error setting (bootloader) baudrate to iProgramSpeed (= 1000000) to /tmp/flasher.log
Error setting (bootloader) baudrate to iProgramSpeed (1000000) (0)
Logging Error setting (bootloader) baudrate to iProgramSpeed (= 1000000) to /tmp/flasher.log
root@Xiaomi_Mijia_Gateway:~#

**Comment by igorlistopad** [comment]
Hi, means that the zigbee port of the module is busy.
You must stop any software that interacts with the module.

**Comment by josejlpd** [comment]
> Hola, significa que el puerto zigbee del módulo está ocupado.
> Debe detener cualquier software que interactúe con el módulo.
thanks bro
I feel like a donkey for not realizing
close this question
