### ISSUE TITLE
About on/off cluster

### ISSUE THREAD

**Issue by muniter** [igo-r/Lumi-Router-JN5169#3]
Hello, I'm an user of this firmware which I find great! Thank you for your work. I wanted to ask a question related to the last release [2021.2.19](https://github.com/igo-r/Lumi-Router-JN5169/releases/tag/2021.2.19). In the notes It says *" Removed On/Off Cluster"* I was wondering if this means there won't be any more an entity/switch/toggle that the device currently presents. Right now I use this function extensively to check if the device is actually able to receive and send messages in my network (Using ZHA in Home Assistant).

**Comment by igorlistopad** [comment]
Hello, in release 2021.2.19 the Device Temperature Configuration Cluster has appeared, and reporte are configured on it to check the operation of the device. All that is needed is for the coordinator to bind to this cluster.

**Comment by muniter** [comment]
I understand one can get the device temperature by "getting the zigbee attribute" I imagine there's something I have to do to make it show app as a sensor for the device in Home Assistant. I would look into it.

![image](https://user-images.githubusercontent.com/9699804/109681233-45475b00-7b4b-11eb-9132-c836ea6c2be2.png)

But I still believe is a nicer feature to just have an on/off "entity" so one can toggle it and see if things are working, Instead of asking the device to report It's temperature. I personally tried "stress testing" the network and making sure the device was getting traffic by just turning the toggle on/off. Similar to the CC2531 router firmwares (although the CC2531 does have leds).

**Comment by igorlistopad** [comment]
The firmware is designed primarily with its use in the z2m network in mind.
But I still don't understand why to check if the device is really capable of receiving and sending messages.
If the device is online, it means that it is working properly.
It is more convenient to track the device whether it is online by the latest report.

**Comment by muniter** [comment]
I haven't used z2m and I'm using the device in ZHA because I would like to have just one zigbee network.

So let me explain my case:

I have the router, ZHA tells me when the device was last seen, this last seen can be triggered by activity on the network, If I have a an "on/off" cluster in the device I can trigger that cluster to change state from HA, which tries to get the message to the Router and sometimes it may reach it, or if the network is failing it may not. 

Having an "on/off" cluster makes it really easy to know if the device is actually receiving messages and able to send and be heard. Since the on/off cluster sends a *"confirmation/state update"* when it toggles the "on/off".

So maybe I'm having problem with some of the end devices that I have connected through this router, so If I want to check if the router is not the problem I can just send a toggle to the on/off cluster and if I get a response I know there's no problem in the router and must be the end device.

Right now I went back to version 2021.1.26 because my network is unstable and I'm testing things all the time, and need this feature. I would love to have it back, but I understand you prefer otherwise. In the future when my network is more stable I will probably update.

**Comment by igorlistopad** [comment]
In order to check whether the router is a problem, it is enough to see that the router sends reports. That is why the function of sending the device temperature automatically (report) was implemented in order to see that the router is working.
In order to automatically update last seen.

In order for reports, the coordinator must be bind to the Device Temperature Configuration cluster.

**Comment by muniter** [comment]
I understand, ideally the Router once connected should present itself with a sensor (Device Temperature Configuration cluster). Or manual configuration is expected?

**Comment by igorlistopad** [comment]
It depends on the software that you are using, it can either automatically display and configure the binding, or you need a convector, or you need to manually configure it.
I'm not familiar with ZHA.

**Comment by muniter** [comment]
@igo-r On an unrelated note, what's the maximum amount of end devices that can connect to the router?

**Comment by igorlistopad** [comment]
> @igo-r On an unrelated note, what's the maximum amount of end devices that can connect to the router?

I didn't run any tests. I know that 20 definitely work.
