### ISSUE TITLE
Firmware for other devices on the JN5169 chip (Прошивка на другие устройства на чипе JN5169)

### ISSUE THREAD

**Issue by VOVAiS** [igo-r/Lumi-Router-JN5169#4]
Hello.
After a failed upgrade of the QBCZ11LM socket, it died (details https://github.com/Koenkk/zigbee-OTA/pull/28)

Is it possible to make a new firmware to the outlet to restore functionality?

Здравствуйте. 
После неудачного обновления розетки QBCZ11LM она умерла (подробности https://github.com/Koenkk/zigbee-OTA/pull/28)

Возможно ли сделать новую прошивку на розетку для восстановления  работоспособности?

**Comment by igorlistopad** [comment]
Здравствуйте.

Не совсем понимаю причем здесь этот репозиторий?
Здесь может обсуждаться прошивка исключительно Xiaomi DGNWG05LM и Aqara ZHWG11LM.

**Comment by VOVAiS** [comment]
Я не знал как по другому спросить. Хорошо закрываю

**Comment by igorlistopad** [comment]
Прошивок для QBCZ11LM увы нет, писать ее ради восстановления работы одной розетки явно не целесообразно, вам проще купить новую розетку.
