### ISSUE TITLE
ERROR: Did not find a cmdline Flattened Device Tree

### ISSUE THREAD

**Issue by pasikov123** [igo-r/Lumi-Router-JN5169#6]
Добрый день! 
После попытки обновления шлюз DGNWG05LM перестал запускаться , не подскажите как откатиться  ?

## Enter main_loop() Now##
Normal Boot
Hit any key to stop autoboot:  0

NAND read: device 0 offset 0x300000, size 0x700000
 7340032 bytes read: OK

NAND read: device 0 offset 0xa00000, size 0x100000
 1048576 bytes read: OK
Kernel image @ 0x80800000 [ 0x000000 - 0x2abfb8 ]
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree

**Comment by igorlistopad** [comment]
Доброго времени!

Немного не по теме, обсудить кастомные прошивки шлюза и проблемы можно здесь: https://t.me/xiaomi_gw_hack

Здесь принимаются вопросы исключительно по прошивке чипа Zigbee.
