### ISSUE TITLE
Aqara ZHWG11LM doesn't pair

### ISSUE THREAD

**Issue by danielk117** [igo-r/Lumi-Router-JN5169#7]
Hi,

I try to use your firmware on my Aqara ZHWG11LM (latest openlumi firmware). 

```
root@OpenLumi:~# jnflash /tmp/LumiRouter.bin
Flash /tmp/LumiRouter.bin
JennicModuleProgrammer Version: 0.11 (r1234)
Logging Serial port opened at iInitialSpeed (= 38400) to /tmp/flasher.log
Setting baudrate for port 3 to 1000000
Detected Chip: JN5169
MAC Address:   00:15:8D:00:05:XX:XX:XX
Erasing = 0%
Writing = 100%
Success!
root@OpenLumi:~# jntool router_mode
Erasing PDM...
set device type = router
Starting network scan
```

Seems to be all fine, but it doesn't connect to my network (zigbee2mqtt with ZBBridge, joining is allowed)...

Any idea whats going wrong or how to debug this?

**Comment by igorlistopad** [comment]
Hi, do everything strictly according to the manual.

You will execute the `jntool router_mode` command, which does not need to be used at all.

The connection process is described here.
https://github.com/igo-r/Lumi-Router-JN5169#pairing

**Comment by danielk117** [comment]
@igo-r I swear I tried this couple of times... (and other as I posted above)
```
jnflash /tmp/LumiRouter.bin
jntool erase_pdm
```
But it was working now, thanks 😉
