### ISSUE TITLE
Device drops from network

### ISSUE THREAD

**Issue by mihaimdinca** [igo-r/Lumi-Router-JN5169#8]
I have 3 Aqara Gateway devices flashed with OpenWrt. The ZigBee chip is flashed with your firmware and all 3 act as routers. All 3 devices are the same model and are connected to ZigBee2MQTT (Sonoff Zigbee Dongle-P CC2652P coordinator). One of them constantly falls from the network and the devices paired to if go offline as well. I tried to pair the device again and also reflashed the ZigBee chip. I still do not know what the problem is. Any suggestions?

**Comment by igorlistopad** [comment]
What is the Linkquality of this device?
How many devices are connected to this device?

**Comment by mihaimdinca** [comment]
I only pair one device to this router directly but after a while, 10-15 devices have routes that include it. The link quality is not very good 60-80. I have a two floor house and there is insulation with metal foil between floors. That restricts the signal an that is why I was hoping to use this router to improve it.

**Comment by igorlistopad** [comment]
Try to place another device in that place, check how it will behave.

**Comment by mihaimdinca** [comment]
I did that yesterday. I am waiting to see the effects. It used to take several days before it dropped.

**Comment by mihaimdinca** [comment]
Everything worked fine until I shut down Home Assistant for a few hours to do some changes to the power circuit. The coordinator was powered down as well as it is connected to the raspberry pi that runs Home Assistant OS and ZigBee2MQTT. After restarting, everything reconnected except for the Aqara Gateway (Open Lumi).

**Comment by igorlistopad** [comment]
Does disconnecting/turning on the gateway from the power supply solve the problem?

**Comment by mihaimdinca** [comment]
Yes

**Comment by igorlistopad** [comment]
> Everything worked fine until I shut down Home Assistant for a few hours to do some changes to the power circuit. The coordinator was powered down as well as it is connected to the raspberry pi that runs Home Assistant OS and ZigBee2MQTT. After restarting, everything reconnected except for the Aqara Gateway (Open Lumi).

I turned off the coordinator (Sonoff Zigbee Dongle-P CC2652P) for 4 hours, when I turned on the coordinator, the router returned back to the network.
I have not been able to reproduce your problem.

**Comment by mihaimdinca** [comment]
I understand. Thank you for trying. As I said, I have 3 Aqara Gateways. The first that showed problems (randomly dropping from the network) I moved it somewhere else and also stopped using it as a router. The one that I put in its place does not (yet) drop from the network but fails to reconnect after the coordinator has been off for some time. It has an LQI around 60. The third one (also the closest to the coordinator, LQI 123) recoverd with no issues.
